[package]
name = "orderbook"
version = "0.1.0"
edition = "2021"

[dependencies]
rust_decimal = "1.23.1"
rust_decimal_macros = "1.23.1"
priority-queue = "1.2.1"
serde = { version = "1.0", features = ["derive"] }


[dev-dependencies]
serde_json = "1.0"
insta = "1.13.0"